
// This file is generated by gen_api.py,
// !! DO NOT edit this file manually

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/complex.h>
#include <pybind11/functional.h>
#include <pybind11/chrono.h>

#include "add.hpp"


namespace py = pybind11;


PYBIND11_MODULE(add, m) {
    m.doc() = "";
    auto m_test = m.def_submodule("test", "add.test module");
    m_test.def("add", static_cast<int (*)(int, int)>(&add::test::add), py::return_value_policy::take_ownership, "My function, add two integer.\n\nArgs:\n  - a: arg a, int type\n  - b: arg b, int type\n\n\nReturns: int type, will a + b\n", py::arg("a") , py::arg("b") );
}
